### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Violet-Scarelli** [MuradAkh/LittleLogistics#75] opened 2022-02-15 04:33 UTC
[crash-2022-02-14_20.31.29-server.txt](https://github.com/MuradAkh/LittleLogistics/files/8065830/crash-2022-02-14_20.31.29-server.txt)
Occurs when a barge train is in motion.

**Comment by MuradAkh** [comment] 2022-02-15 07:54
Hey, could you provide more info?
Did the crash happen with older version? 
Can you confirm if it's a comparability issue (are you able to play the mod by itself)

We will try to get this fixed

**Comment by Violet-Scarelli** [comment] 2022-02-15 21:52
The crash only seems to occur on multiplayer.

**Comment by MuradAkh** [comment] 2022-02-16 01:08
We've tested this mod in multiplayer before without issues. My suspicion is that this is likely an interaction with another mod. It would be helpful if you could help narrowing down the potential mod list

**Comment by EDToaster** [comment] 2022-02-16 01:32
Can reproduce, seems to be the fact that `Entity.isColliding` only exists on the client side

https://github.com/MuradAkh/LittleLogistics/blob/3f5d7068ed7c1df4f9b21ab1622beadf74dc9508/src/main/java/dev/murad/shipping/entity/custom/SpringEntity.java#L219

**Comment by MuradAkh** [comment] 2022-02-16 03:05
Fixed in 1.0.4

**Closed** 2022-02-16 03:05 UTC
Labels: bug, critical
