### ISSUE TITLE
Chunk loader train car teleported to another dimension may leave chunks permanently force-loaded

### ISSUE THREAD

**Issue by TheRealWormbo** [MuradAkh/LittleLogistics#195] opened 2022-07-15 09:11 UTC
I experimented with sending chunk loader train carts between dimensions using the Waystones mod's warp plate and it seems I somehow created a permanently loaded 3x3 area of chunks in the end that have a Forge entity loading ticket associated with a non-existing entity in that dimension.

Mod pack: The Phoenix's Magics and Goodies (version 1.3)
Forge: 40.1.54
Little Logistics: 1.18.2-v1.2.5
Waystones: 1.18.2-10.1.0

To send the chunk loader train car between the overworld and the end I used the following pair of contraptions:
![Overworld side](https://user-images.githubusercontent.com/7620864/179190502-3162fb33-71e6-4201-8d16-394c194ba8c2.png)
![End side](https://user-images.githubusercontent.com/7620864/179190508-86425de9-2803-47fe-b37f-1e6707ec0ec9.png)
The additional dispenser setup in the end was a test to send vanilla minecarts back to the overworld to confirm that the end was still entity processing even if the overworld side was no longer sending the chunk loader train car back to the end. (I saw minecarts still arriving in 10 second intervals, which is the delay produced by the two Create pulse repeaters in the screenshot.)

Notably, when the chunk loader train car arrives in the end for the first time, it will not load the area it arrived in. Only when I follow it via the warp plate (or a vanilla end portal), the end chunks will become loaded, which can be confirmed by returning to the overworld. The chunk loader train cart will now loop between the two pairs of warp plates without a player being present in the end.

I have taken a look at the world save with NBTExplorer and can see in the `chunks.dat` files for the overworld and end dimensions that each have 9 chunks loaded for the same entity UUID, stating "littlelogistics" as the mod. Breaking the chunk loader train car in the overworld cleared its loaded overworld chunks, but the end chunks still are force-loaded without any chunk loader train cars around.

**Comment by MuradAkh** [comment] 2022-07-30 19:35
Thank you for the report! Very thorough! I would be interested to know if you can reproduce this with vanilla nether portals too?

**Comment by TheRealWormbo** [comment] 2022-07-30 20:12
I can confirm it happens with vanilla teleportation methods as well, both with nether portals and end portals. If the chunk loader switches dimensions, it does not remove the force-loading in the dimension it left.

**Comment by MuradAkh** [comment] 2022-12-02 02:30
we ended up getting rid of chunkloader cars completely in 1.19, the new system should not have this problem. Won't be fixed in 1,18 since there is no easy fix

**Closed as completed by MuradAkh** 2022-12-02 02:30 UTC
Labels: bug
