### ISSUE TITLE
issue with server config forge 1.18.2

### ISSUE THREAD

**Issue by itsdinkd** [MuradAkh/LittleLogistics#193] opened 2022-06-16 23:34 UTC
```java
[16Jun2022 16:29:12.001] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file G:\mc\Instances\AQM3 1.18.2\saves\New World (1)\serverconfig\littlelogistics-server.toml is not correct. Correcting
[16Jun2022 16:29:12.001] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key vessel.general.vesselInvuln was corrected from [create.mechanical_saw, create.mechanical_drill] to its default, [create.mechanical_saw, create.mechanical_drill]. 
[16Jun2022 16:29:12.001] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key train.general.trainInvuln was corrected from [create.mechanical_saw, create.mechanical_drill] to its default, [create.mechanical_saw, create.mechanical_drill]. 
```

makes zero sense as its literally correcting its default value, which is also wrong (the name space is incorrect)

**Comment by MuradAkh** [comment] 2022-06-17 04:41
Could you please explain what you mean by "the namespace is incorrect"

I am a bit confused by the error message, not sure why it's triggered or what it means. 

The string values in the list are correct, they are the IDs/msg names of DamageSources related to those create actors, not IDs of blocks or entities

**Comment by MuradAkh** [comment] 2022-06-17 04:45
Could you provide some context on when you see this message, I can see if I can reproduce it and reach out to Forge and see what's causing it

**Comment by MuradAkh** [comment] 2022-06-20 02:43
Had a better look at this, the reason for this issue is that we aren't calling the right define method in the config for lists. Will be fixed in the next release.

**Closed as completed** 2022-08-14 19:05 UTC
Labels: bug

**Comment by itsdinkd** [comment] 2022-08-14 23:16
> Had a better look at this, the reason for this issue is that we aren't calling the right define method in the config for lists. Will be fixed in the next release.

in the default config you wrote create.mechanical_saw where it should be create:mechanical_saw.

You cannot change it in the file because if you do the config gets reset again and will write in "create.mechanical.blade"

The problem is you used a "." after the modid, create, instead of a ":"

**Comment by itsdinkd** [comment] 2022-08-14 23:19
The commit is still incorrect. 

```
List.of("create.mechanical_saw"
 ...
```

Should be 

```
List.of("create:mechanical_saw"
 ...
```

**Comment by MuradAkh** [comment] 2022-08-15 04:24
@itsdinkd no this is in fact correct. This is a damage source name not an entity ID or anything. Damage source "names" were defined with a dot by create, unless this changed in 0.5. 

The correction issue should be fixed in 1.2.6, it was unrelated to the namespace and was because validation was because config lists were defined incorrectly. If you can reproduce this issue in 1.2.6 please let me know

**Comment by MuradAkh** [comment] 2022-08-15 04:26
You can see it defined with a dot not a column here: 
https://github.com/Creators-of-Create/Create/blob/858fbd5c1a12f620fa83f69abff038d771681b8a/src/main/java/com/simibubi/create/content/contraptions/components/saw/SawBlock.java

**Comment by itsdinkd** [comment] 2022-08-15 05:12
Ah I see. Thank you for the clarification and the fix
