### ISSUE TITLE
Crash When Open the "Tug Route" GUI

### ISSUE THREAD

**Issue by OcrSu** [MuradAkh/LittleLogistics#150] opened 2022-03-28 23:34 UTC
[crash-2022-03-29_07.26.31-client.txt](https://github.com/MuradAkh/LittleLogistics/files/8366951/crash-2022-03-29_07.26.31-client.txt)

Crash When Open the "Tug Route"(By Shift and Right Click)

ModPack:https://www.curseforge.com/minecraft/modpacks/lcw/files
Version:3.4.5

**Comment by MuradAkh** [comment] 2022-03-29 04:25
Thanks for reporting! Does this always happen? Were you able to open it previously? 

Will get a fix released asap

**Comment by MuradAkh** [comment] 2022-03-29 04:32
This appears to be caused by "Modern UI" mixins. We will try to fix it on our end but please report it to them as well

**Comment by OcrSu** [comment] 2022-03-29 08:28
> This appears to be caused by "Modern UI" mixins. We will try to fix it on our end but please report it to them as well

it is my first time to put this mod"LittleLogistics" into my modpack
I have reported to them(ModernUI)

**Comment by MuradAkh** [comment] 2022-03-29 23:17
@OcrSu could you please link your report/issue with ModernUI

**Comment by OcrSu** [comment] 2022-03-30 06:23
emm.
![QQ图片20220330142226](https://user-images.githubusercontent.com/75876201/160764891-d2cc1cba-d141-4fc3-b69d-deb738c6a9d2.png)
.

**Comment by OcrSu** [comment] 2022-03-30 06:24
@MuradAkh

**Comment by EDToaster** [comment] 2022-03-30 07:18
Thanks for the report, we'll take a look.

**Comment by MuradAkh** [comment] 2022-03-31 21:58
Is this issue limited to 1.16.5 then?

**Comment by OcrSu** [comment] 2022-03-31 23:23
> 那么这个问题仅限于1.16.5吗？

https://paste.loliidc.cn/?2240dd4de7f7b43e#FLYmyQBiL6LbAcm2nuvkQun4UKJM3WiwoCSmygxs1Tf2
This is also the case in 1.18.2

**Comment by OcrSu** [comment] 2022-03-31 23:25
https://www.curseforge.com/minecraft/modpacks/lost-civilization-nature/files

ModPack:Lost_Civilization:Nature1.0 and add littlelogistics-mc1.18.2-v1.1.7.jar

**Comment by OcrSu** [comment] 2022-04-01 00:16
![20220401081521](https://user-images.githubusercontent.com/75876201/161170450-c453d79e-da62-49af-b58e-689c7e220658.png)
Only In 1.18.2 ,can do this...

> https://www.curseforge.com/minecraft/modpacks/lost-civilization-nature/files
> 
> ModPack:Lost_Civilization:Nature1.0 and add littlelogistics-mc1.18.2-v1.1.7.jar

**Comment by MuradAkh** [comment] 2022-04-06 00:41
I don't think we will be trying to fix this for 1.16 as it's caused by a modernui mixin. 
Glad they added a workaround for 1,18
Seems very niche and we have a lot on our plates, I am not sure if there's a simple fix,. but if someone finds one PRs are welcome

**Closed as completed by MuradAkh** 2022-04-06 00:41 UTC
Labels: wontfix, compatibility
