### ISSUE TITLE
Console keeps trying to correct the config file but never does. Results in massive server lag.

### ISSUE THREAD

**Issue by cleavercp** [MuradAkh/LittleLogistics#200] opened 2022-08-02 18:36 UTC
My servers console keeps pinging this none-stop.

[02Aug2022 11:32:58.258] [Thread-0/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file /var/games/minecraft/servers/AllTheMods7/./world/serverconfig/littlelogistics-server.toml is not correct. Correcting

What can I do to make it stop?

**Comment by MuradAkh** [comment] 2022-08-03 03:32
This is a duplicate of #193. Will be patched in the next update. My impression was that this only happens on start up, and certainly shouldn't cause "massive server lag". Not quite sure what's the root cause of the lag, but I will try to roll out an update out asap if this is indeed the reason 

How often are you seeing these messages?

**Closed as completed** 2022-08-13 19:58 UTC
Labels: duplicate
