### ISSUE TITLE
mc1.18.2 - v1.2.5 server config error spewing

### ISSUE THREAD

**Issue by HelpImDying** [MuradAkh/LittleLogistics#204] opened 2022-08-15 01:30 UTC
When staring a server on either Unbutu 20.04 LTS forge-1.18.2-40.1.68 the Little Logistics mod start spewing an error. Shortly after the world starts generating the little logistics mod start spewing "/world/serverconfig/littlelogistics-server.toml is not correct. Correcting". The mod is making creating the file than complaining about the file just created than making a backup and recreated an identical file.
I have added a txt extension to the two of the config files

[littlelogistics-server.toml.txt](https://github.com/MuradAkh/LittleLogistics/files/9334545/littlelogistics-server.toml.txt)
[littlelogistics-server-5.toml.bak.txt](https://github.com/MuradAkh/LittleLogistics/files/9334546/littlelogistics-server-5.toml.bak.txt)

**Comment by MuradAkh** [comment] 2022-08-15 04:20
This was fixed in the last release, please update the mod. You should be able to just update the jar on the server to fix the issue, without waiting for a pack update 

Duplicate of #193

**Closed as completed** 2022-08-15 04:20 UTC
Labels: duplicate
